### ISSUE TITLE
Crashes when sending a report (Linux)

### ISSUE THREAD

**Issue by yaomtc** [goatcorp/Dalamud#1049]
Whenever I hit Send on a report in-game, the game crashes. I need to use the official launcher to successfully send. Here is a screenshot of the error.
![Screenshot_20230101_155404](https://user-images.githubusercontent.com/5534045/210185731-3168db84-119b-4006-90f3-f3182355387f.png)

**Comment by NotNite** [comment]
Does this happen without any plugins enabled? Could you send your `dalamud.log`?

**Comment by yaomtc** [comment]
I just disabled the plugins and tried sending a reply to the support desk, and it happened again. Where can I find `dalamud.log`?

**Comment by raaben** [comment]
I received the same error trying to send a report today. Disabling addons did not fix it, and disabling Dalamud resulted in a crash but with a different message when attempting to send:

![image](https://user-images.githubusercontent.com/4754408/212575451-8785215e-9bb9-4dfe-9e8a-c3f9c90cce8d.png)

Nothing crash related seems to be logged in dalamud.log or launcher.log after disabling Dalamud, despite the crash. From before I disabled, the relevant part in dalamud.log seems to be:

2023-01-15 19:02:49.265 -05:00 [FTL] Unhandled exception on AppDomain
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 458
2023-01-15 19:02:49.266 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wMS0xNVQxOTowMjo0OS4yNjYwNTgzLTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5BY2Nlc3NWaW9sYXRpb25FeGNlcHRpb246IEF0dGVtcHRlZCB0byByZWFkIG9yIHdyaXRlIHByb3RlY3RlZCBtZW1vcnkuIFRoaXMgaXMgb2Z0ZW4gYW4gaW5kaWNhdGlvbiB0aGF0IG90aGVyIG1lbW9yeSBpcyBjb3JydXB0LlxyXG4gICBhdCBEYWxhbXVkLkdhbWUuRnJhbWV3b3JrLkhhbmRsZUZyYW1ld29ya1VwZGF0ZShJbnRQdHIgZnJhbWV3b3JrKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxHYW1lXFxGcmFtZXdvcmsuY3M6bGluZSA0NTgiLCJDb250ZXh0IjoiRGFsYW11ZFVuaGFuZGxlZCJ9
2023-01-15 19:02:52.399 -05:00 [INF] User chose to disable plugins on next launch...

**Comment by yaomtc** [comment]
How do you find `dalamud.log`? I couldn't find where that's documented.

**Comment by reiichi001** [comment]
It will be in `%appdata%\xivlauncher` (Should bring you to `C:\Users\<windows username>\Appdata\Roaming\XIVLauncher`)

**Comment by yaomtc** [comment]
On Linux, that's in `~/.xlcore/`.

[dalamud.log](https://github.com/goatcorp/Dalamud/files/11582572/dalamud.log)

**Comment by thembees** [comment]
I'm also having an issue similar to this, for me the dalamud.log file is not in ~/.xlcore/ it's in ~/.xlcore/wineprefix/drive_c/users/z/AppData/Roaming/XIVLauncher/

Here mine is: 
`2023-08-30 18:50:15.527 -06:00 [FTL] Unhandled exception on AppDomain
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 487
2023-08-30 18:50:15.528 -06:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOC0zMFQxODo1MDoxNS41MjgwMDktMDY6MDAiLCJJbmZvIjoiU3lzdGVtLkFjY2Vzc1Zpb2xhdGlvbkV4Y2VwdGlvbjogQXR0ZW1wdGVkIHRvIHJlYWQgb3Igd3JpdGUgcHJvdGVjdGVkIG1lbW9yeS4gVGhpcyBpcyBvZnRlbiBhbiBpbmRpY2F0aW9uIHRoYXQgb3RoZXIgbWVtb3J5IGlzIGNvcnJ1cHQuXHJcbiAgIGF0IERhbGFtdWQuR2FtZS5GcmFtZXdvcmsuSGFuZGxlRnJhbWV3b3JrVXBkYXRlKEludFB0ciBmcmFtZXdvcmspIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEdhbWVcXEZyYW1ld29yay5jczpsaW5lIDQ4NyIsIkNvbnRleHQiOiJEYWxhbXVkVW5oYW5kbGVkIn0=
`

**Comment by yaomtc** [comment]
Interesting, I don't have an XIVLauncher folder there, just the usual Microsoft folder. Do you have FFXIV on Steam or standalone?

**Comment by thembees** [comment]
@yaomtc I have xiv installed via Steam, the only 'non-standard' thing I'm doing is using proton-ge-custom as my wine runner, **however** I have tried setting it to use the default wine version and the dalamud.log is still in the same weird location ( ~/.xlcore/wineprefix/drive_c/users/z/AppData/Roaming/XIVLauncher/ )

**Comment by yaomtc** [comment]
This seems to be resolved now, I just submitted a report and the game didn't crash.
