### ISSUE TITLE
Plugins loading unmanaged DLLs that depend on other unloaded unmanaged DLLs causes a load failure

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/Dalamud#1238]
Say that one ten times fast 🤖

When a plugin loads an unmanaged DLL via P/Invoke, that triggers the custom AssemblyLoadContext implementation, which redirects unmanaged DLL loads ([1](https://github.com/goatcorp/Dalamud/blob/5a8fff515fc93becd1f96b598da25ada88b3a65f/Dalamud/Plugin/Internal/Loader/ManagedLoadContext.cs#L205)) to a shadow assembly ([2](https://github.com/goatcorp/Dalamud/blob/5a8fff515fc93becd1f96b598da25ada88b3a65f/Dalamud/Plugin/Internal/Loader/ManagedLoadContext.cs#L353)) to enable hot-reloading. The implementation creates a copy of the assembly in a temporary directory (`AppData/Local/Temp/...` on Windows) and locks that copy for loading instead of the original copy. However, it does not copy any of that assembly's dependencies to the shadow location.

When the assembly attempts to call into a DLL it depends on, that bypasses the custom import logic (as expected, since it's an unmanaged import) and uses the standard `LoadLibrary` semantics, which can fail to find the required DLLs relative to the new shadow location. This is not an issue if the libraries in question are already installed system-wide, and may not be an issue if the libraries are already loaded as process modules, but if any other libraries are needed that don't fulfill these conditions, the load will fail, causing the plugin to throw an exception at the call site back in managed land.

My use case is bundling `libav` with a plugin to perform video decoding - I can't use C++/CLI to avoid the indirect load because plugins are loaded as collectible assemblies ([more details](https://github.com/dotnet/coreclr/pull/23430)), so my next best option is to wrap the functionality I need from `libav` in a simple C++ class, which I can then load directly with a small number of P/Invoke declarations. I would prefer not to directly import from `libav`, because I would need a dozen or more function declarations and a few dozen structs besides.

I can think of a few workarounds for this:
- Bite the bullet and write a bunch of interop boilerplate for `libav` to directly import it
- Statically-link against `libav` so I can directly import my wrapper DLL without indirectly loading the `libav` DLLs (I tried this and got a wall of linker errors, but I might come back to it)
- Attempt to force all of my indirect dependencies to load into the process space first by either calling `LoadLibrary` on them from managed code or calling some random function from each of them with P/Invoke to trigger the intended import logic

When I rebuild Dalamud with shadow assemblies disabled (just flipping [this](https://github.com/goatcorp/Dalamud/blob/5a8fff515fc93becd1f96b598da25ada88b3a65f/Dalamud/Plugin/Internal/Loader/AssemblyLoadContextBuilder.cs#L283) to false) everything loads correctly, so it would be ideal if either:

1. Shadow assembly loading were optional for specific assemblies, accepting that hot-reloading will break if you do that
2. Shadow assembly loading were changed to somehow detect dependencies and shadow-load them, too

I think one of my planned workarounds will work for me, and this seems to be a narrow edge case since seemingly nobody else has run into this, but I'm opening this anyways since it's an extremely unintuitive bug.

**Comment by goaaats** [comment]
Can you attach a minimal repro?

**Comment by karashiiro** [comment]
Here: https://github.com/karashiiro/Dalamud1238
I vendored the native DLLs for convenience, but you can rebuild them, just copy them to the repository root afterwards so that they get copied to the plugin output directory.

The load order should be:
```
Dalamud1238 -> DynamicLibrary1 -> DynamicLibrary2
```

This fails with:
```
2023-06-04 08:05:27.223 -07:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load DLL 'C:\Users\karashiiro\AppData\Local\Temp\x0yif3l4.fza\DynamicLibrary1.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.<LoadFromPath>g____PInvoke|1_0(UInt16* libraryName, Int32 throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromShadowCopy(String unmanagedDllPath) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 361
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromResolvedPath(String unmanagedDllPath, Boolean normalizePath) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 352
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDll(String unmanagedDllName) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Loader\ManagedLoadContext.cs:line 262
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at Dalamud1238.Dalamud1238.Product(Int32 a, Int32 b)
   at Dalamud1238.Dalamud1238..ctor() in D:\Users\luca\Documents\GitHub\Dalamud1238\Dalamud1238.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 119
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 444
```

**Comment by karashiiro** [comment]
At the moment, I've confirmed this works as a workaround:

```csharp
[ModuleInitializer]
[SuppressMessage("Usage", "CA2255:The \'ModuleInitializer\' attribute should not be used in libraries")]
public static void Initialize()
{
    NativeLibrary.Load(ResolvePath("avcodec-59.dll"));
    NativeLibrary.Load(ResolvePath("avformat-59.dll"));
    NativeLibrary.Load(ResolvePath("avcodec-59.dll"));
    NativeLibrary.Load(ResolvePath("avutil-57.dll"));
    NativeLibrary.Load(ResolvePath("swresample-4.dll"));
    NativeLibrary.Load(ResolvePath("swscale-6.dll"));
}
```

**Comment by Minoost** [comment]
You can workaround this by inserting a custom dll resolver.

```csharp
public sealed class Plugin : IDalamudPlugin {
    public Plugin() {
        var currentAlc = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
        if (currentAlc != null)
        {
            currentAlc.ResolvingUnmanagedDll += CustomAssemblyResolver.ResolveUnmanaged;
        }

        // do things...
    }

    public void Dispose()
    {
        var currentAlc = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
        if (currentAlc != null)
        {
            currentAlc.ResolvingUnmanagedDll -= CustomAssemblyResolver.ResolveUnmanaged;
        }
    }
}

internal static class CustomAssemblyResolver
{
    public static nint ResolveUnmanaged(Assembly assembly, string library)
    {
        var assemblyLocation = Path.GetDirectoryName(assembly.Location);
        if (assemblyLocation is null)
        {
            return nint.Zero;
        }

        var path = Path.Combine(assemblyLocation, library);
        Log.Information("ResolvePath: {Path}", path);

        if (NativeLibrary.TryLoad(path, out var handle))
        {
            return handle;
        }

        return nint.Zero;
    }
}
```

![Untitled](https://github.com/goatcorp/Dalamud/assets/1381835/ed2b2c38-50ae-4809-a221-81512009cdbe)

**Comment by Glorou** [comment]
Just going to bump this issue, it seems to have started up again when using OtterTex for my plugin for a user, tried to resolve using the workarounds above but I think due to me not having the direct dependency on the Unmanaged DLL I and rather using it via a C# wrapper its not having any affect. Any help would be appreciated o/
```System.DllNotFoundException: Unable to load DLL 'C:\Users\cmlin\AppData\Local\Temp\rzzl5dso.wvx\DirectXTexC.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromShadowCopy(String unmanagedDllPath) in /_/Dalamud/Plugin/Internal/Loader/ManagedLoadContext.cs:line 371
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromResolvedPath(String unmanagedDllPath, Boolean normalizePath) in /_/Dalamud/Plugin/Internal/Loader/ManagedLoadContext.cs:line 362
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDll(String unmanagedDllName) in /_/Dalamud/Plugin/Internal/Loader/ManagedLoadContext.cs:line 272
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at OtterTex.ScratchImage.<scratchimage_release>g____PInvoke|20_0(ScratchImageData* data)
   at OtterTex.ScratchImage.scratchimage_release(ScratchImageData& data)
   at OtterTex.ScratchImage.Dispose()
   at OtterTex.ScratchImage.Finalize()
   at System.GC.RunFinalizers()
```

**Comment by allandiego** [comment]
Im having the same issue, dalamud wont load Native dlls from this lib even though they exist in the build folder

<img width="326" height="241" alt="Image" src="https://github.com/user-attachments/assets/0c244efb-1ebc-437f-bd18-058dea65a1cc" />

https://www.nuget.org/packages/Melanchall.DryWetMidi
```xml
<PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
```

demo repo:
https://github.com/zunetrix/ZunePlayer

The workaround I'm using is to copy the DLLs to the runtime folder
AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\10.0.0

```c#
12:15:25.966 | ERR | [LOCALPLUGIN] Error while loading "ZunePlayer", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create ZunePlayer.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.DllNotFoundException: Unable to load DLL 'Melanchall_DryWetMidi_Native64' or one of its dependencies. (0x8007007E)
	   at Melanchall.DryWetMidi.Multimedia.TickGeneratorSessionApi64.OpenTickGeneratorSession(IntPtr& handle)
	   at Melanchall.DryWetMidi.Multimedia.TickGeneratorSession.GetSessionHandle()
	   at Melanchall.DryWetMidi.Multimedia.HighPrecisionTickGenerator.Start(TimeSpan interval)
	   at Melanchall.DryWetMidi.Multimedia.MidiClock.Restart()
```

**Comment by allandiego** [comment]
Workaround2: added a resolver to load dlls from the plugin path so you don't need to copy it to the runtime folder

```csharp
    public Plugin(IDalamudPluginInterface pluginInterface) {
        pluginInterface.Create<DalamudApi>();
        DryWetMidiNativeResolver.Register();

        Config = pluginInterface.GetPluginConfig() as Configuration ?? new Configuration();
        Config.Initialize(DalamudApi.PluginInterface);
// ...
}

    public void Dispose() {
// ...

        PlaybackTicker.Ticked -= PlaybackTickerTicked;
        PlaybackTicker.Stop();
        PlaybackTicker.Dispose();

        DryWetMidiNativeResolver.Unregister();
        Ui.Dispose();
    }
```


```csharp
internal static class DryWetMidiNativeResolver {
    private static bool _registered;

    public static void Register() {
        if (_registered)
            return;

        var alc = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
        if (alc == null)
            return;

        alc.ResolvingUnmanagedDll += ResolveUnmanaged;
        _registered = true;

        DalamudApi.PluginLog.Information("[DryWetMidi] Native resolver registered");
    }

    public static void Unregister() {
        if (!_registered)
            return;

        var alc = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
        if (alc == null)
            return;

        alc.ResolvingUnmanagedDll -= ResolveUnmanaged;
        _registered = false;
    }

    private static nint ResolveUnmanaged(Assembly assembly, string libraryName) {
        if (!libraryName.Contains("DryWetMidi", StringComparison.OrdinalIgnoreCase))
            return nint.Zero;

        try {
            var pluginDir = DalamudApi.PluginInterface.AssemblyLocation.Directory?.FullName;
            if (string.IsNullOrEmpty(pluginDir))
                return nint.Zero;

            var fileName = libraryName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)
                ? libraryName
                : libraryName + ".dll";

            var fullPath = Path.Combine(pluginDir, fileName);

            DalamudApi.PluginLog.Information($"[DryWetMidi] Trying load: {fullPath}");

            if (File.Exists(fullPath) &&
                NativeLibrary.TryLoad(fullPath, out var handle)) {
                DalamudApi.PluginLog.Information($"[DryWetMidi] Loaded native: {fileName}");
                return handle;
            }
        } catch (Exception ex) {
            DalamudApi.PluginLog.Error(ex, "[DryWetMidi] Failed to resolve native DLL");
        }

        return nint.Zero;
    }
}
```
