### ISSUE TITLE
DalamudCommands: non-concurrent access exception

### ISSUE THREAD

**Issue by Infiziert90** [goatcorp/Dalamud#1310]
```
2023-07-12 17:15:04.216 +02:00 [ERR] [SVC] Service<DalamudCommands>: Construction failure
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dalamud.Game.Command.CommandManager.AddHandler(String command, CommandInfo info) in C:\goatsoft\companysecrets\dalamud\Game\Command\CommandManager.cs:line 120
   at Dalamud.Interface.Internal.DalamudCommands..ctor(CommandManager commandManager) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\DalamudCommands.cs:line 50
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Dalamud.Service`1.ConstructObject() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 280
   at Dalamud.Service`1.<>c.<<StartLoader>b__9_0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 186
```
   
Happens at startup and prevents the load of dalamud as all services unload after this exception

**Comment by goaaats** [comment]
Probably fine now with https://github.com/goatcorp/Dalamud/commit/1f0526b2ef6f4fd1cd8330bd7ed6293e5ca2621c
