### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by Daedren** [goatcorp/Dalamud#1492]
Hello! After a fresh install (no plugins or anything), the game always crashes after the initial black screen if Dalamud is injected.
Here's the log, if you need any more information please let me know.

<details>
  <summary>dalamud.log</summary>

```
2023-10-11 22:01:04.339 +01:00 [INF] --------------------------------------------------------------------------------
2023-10-11 22:01:04.339 +01:00 [INF] Initializing a session..
2023-10-11 22:01:04.434 +01:00 [INF] This is Dalamud - Core: a7f134b1, CS: c9daf7d4 [2750]
2023-10-11 22:01:04.436 +01:00 [INF] Trying to set up Loc for culture en
2023-10-11 22:01:04.639 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0xMC0xMVQyMjowMTowNC42MzI2MTAxKzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IE9uZSBvciBtb3JlIGVycm9ycyBvY2N1cnJlZC4gKFNwZWNpZmllZCBhcmd1bWVudCB3YXMgb3V0IG9mIHRoZSByYW5nZSBvZiB2YWxpZCB2YWx1ZXMuIChQYXJhbWV0ZXIgJ2xlbmd0aCcpKSAoU3BlY2lmaWVkIGFyZ3VtZW50IHdhcyBvdXQgb2YgdGhlIHJhbmdlIG9mIHZhbGlkIHZhbHVlcy4gKFBhcmFtZXRlciAnbGVuZ3RoJykpXHJcbiAtLS0+IFN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IFNwZWNpZmllZCBhcmd1bWVudCB3YXMgb3V0IG9mIHRoZSByYW5nZSBvZiB2YWxpZCB2YWx1ZXMuIChQYXJhbWV0ZXIgJ2xlbmd0aCcpXHJcbiAgIGF0IEx1bWluYS5EYXRhLkx1bWluYUJpbmFyeVJlYWRlci5SZWFkU3RydWN0dXJlW1RdKClcclxuICAgYXQgTHVtaW5hLkRhdGEuU3FQYWNrSW5kZXguTG9hZEluZGV4KClcclxuICAgYXQgTHVtaW5hLkRhdGEuU3FQYWNrSW5kZXguLmN0b3IoRmlsZUluZm8gaW5kZXhGaWxlLCBHYW1lRGF0YSBnYW1lRGF0YSlcclxuICAgYXQgTHVtaW5hLkRhdGEuUmVwb3NpdG9yeS48PmNfX0Rpc3BsYXlDbGFzczI4XzEuPFNldHVwSW5kZXhlcz5iX18yKClcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5UYXNrcy5UYXNrYDEuSW5uZXJJbnZva2UoKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkV4ZWN1dGlvbkNvbnRleHQuUnVuRnJvbVRocmVhZFBvb2xEaXNwYXRjaExvb3AoVGhyZWFkIHRocmVhZFBvb2xUaHJlYWQsIEV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgQ29udGV4dENhbGxiYWNrIGNhbGxiYWNrLCBPYmplY3Qgc3RhdGUpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bkZyb21UaHJlYWRQb29sRGlzcGF0Y2hMb29wKFRocmVhZCB0aHJlYWRQb29sVGhyZWFkLCBFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIENvbnRleHRDYWxsYmFjayBjYWxsYmFjaywgT2JqZWN0IHN0YXRlKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suRXhlY3V0ZVdpdGhUaHJlYWRMb2NhbChUYXNrJiBjdXJyZW50VGFza1Nsb3QsIFRocmVhZCB0aHJlYWRQb29sVGhyZWFkKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5UYXNrcy5UYXNrLlRocm93SWZFeGNlcHRpb25hbChCb29sZWFuIGluY2x1ZGVUYXNrQ2FuY2VsZWRFeGNlcHRpb25zKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suV2FpdChJbnQzMiBtaWxsaXNlY29uZHNUaW1lb3V0LCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5UYXNrcy5UYXNrLldhaXQoKVxyXG4gICBhdCBMdW1pbmEuRGF0YS5SZXBvc2l0b3J5LlNldHVwSW5kZXhlcyhCb29sZWFuIG11bHRpdGhyZWFkKVxyXG4gICBhdCBMdW1pbmEuRGF0YS5SZXBvc2l0b3J5Li5jdG9yKERpcmVjdG9yeUluZm8gcm9vdERpciwgR2FtZURhdGEgZ2FtZURhdGEpXHJcbiAgIGF0IEx1bWluYS5HYW1lRGF0YS48PmNfX0Rpc3BsYXlDbGFzczMwXzAuPC5jdG9yPmJfXzMoKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2tgMS5Jbm5lckludm9rZSgpXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuRXhlY3V0aW9uQ29udGV4dC5SdW5Gcm9tVGhyZWFkUG9vbERpc3BhdGNoTG9vcChUaHJlYWQgdGhyZWFkUG9vbFRocmVhZCwgRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0LCBDb250ZXh0Q2FsbGJhY2sgY2FsbGJhY2ssIE9iamVjdCBzdGF0ZSlcclxuLS0tIEVuZCBvZiBzdGFjayB0cmFjZSBmcm9tIHByZXZpb3VzIGxvY2F0aW9uIC0tLVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkV4ZWN1dGlvbkNvbnRleHQuUnVuRnJvbVRocmVhZFBvb2xEaXNwYXRjaExvb3AoVGhyZWFkIHRocmVhZFBvb2xUaHJlYWQsIEV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgQ29udGV4dENhbGxiYWNrIGNhbGxiYWNrLCBPYmplY3Qgc3RhdGUpXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuVGFza3MuVGFzay5FeGVjdXRlV2l0aFRocmVhZExvY2FsKFRhc2smIGN1cnJlbnRUYXNrU2xvdCwgVGhyZWFkIHRocmVhZFBvb2xUaHJlYWQpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgTHVtaW5hLkdhbWVEYXRhLi5jdG9yKFN0cmluZyBkYXRhUGF0aCwgTHVtaW5hT3B0aW9ucyBvcHRpb25zKVxyXG4gICBhdCBEYWxhbXVkLkRhdGEuRGF0YU1hbmFnZXIuLmN0b3IoRGFsYW11ZCBkYWxhbXVkKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxEYXRhXFxEYXRhTWFuYWdlci5jczpsaW5lIDYxXHJcbiAtLS0+IChJbm5lciBFeGNlcHRpb24gIzEpIFN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IFNwZWNpZmllZCBhcmd1bWVudCB3YXMgb3V0IG9mIHRoZSByYW5nZSBvZiB2YWxpZCB2YWx1ZXMuIChQYXJhbWV0ZXIgJ2xlbmd0aCcpXHJcbiAgIGF0IEx1bWluYS5EYXRhLkx1bWluYUJpbmFyeVJlYWRlci5SZWFkU3RydWN0dXJlW1RdKClcclxuICAgYXQgTHVtaW5hLkRhdGEuU3FQYWNrSW5kZXguTG9hZEluZGV4KClcclxuICAgYXQgTHVtaW5hLkRhdGEuU3FQYWNrSW5kZXguLmN0b3IoRmlsZUluZm8gaW5kZXhGaWxlLCBHYW1lRGF0YSBnYW1lRGF0YSlcclxuICAgYXQgTHVtaW5hLkRhdGEuUmVwb3NpdG9yeS48PmNfX0Rpc3BsYXlDbGFzczI4XzEuPFNldHVwSW5kZXhlcz5iX18yKClcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5UYXNrcy5UYXNrYDEuSW5uZXJJbnZva2UoKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkV4ZWN1dGlvbkNvbnRleHQuUnVuRnJvbVRocmVhZFBvb2xEaXNwYXRjaExvb3AoVGhyZWFkIHRocmVhZFBvb2xUaHJlYWQsIEV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgQ29udGV4dENhbGxiYWNrIGNhbGxiYWNrLCBPYmplY3Qgc3RhdGUpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bkZyb21UaHJlYWRQb29sRGlzcGF0Y2hMb29wKFRocmVhZCB0aHJlYWRQb29sVGhyZWFkLCBFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIENvbnRleHRDYWxsYmFjayBjYWxsYmFjaywgT2JqZWN0IHN0YXRlKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suRXhlY3V0ZVdpdGhUaHJlYWRMb2NhbChUYXNrJiBjdXJyZW50VGFza1Nsb3QsIFRocmVhZCB0aHJlYWRQb29sVGhyZWFkKTwtLS1cclxuIiwiQ29udGV4dCI6IkNvdWxkIG5vdCBkb3dubG9hZCBkYXRhLiJ9
2023-10-11 22:01:04.626 +01:00 [ERR] Could not download data.
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Lumina.Data.LuminaBinaryReader.ReadStructure[T]()
   at Lumina.Data.SqPackIndex.LoadIndex()
   at Lumina.Data.SqPackIndex..ctor(FileInfo indexFile, GameData gameData)
   at Lumina.Data.Repository.<>c__DisplayClass28_1.<SetupIndexes>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Lumina.Data.Repository.SetupIndexes(Boolean multithread)
   at Lumina.Data.Repository..ctor(DirectoryInfo rootDir, GameData gameData)
   at Lumina.GameData.<>c__DisplayClass30_0.<.ctor>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Lumina.GameData..ctor(String dataPath, LuminaOptions options)
   at Dalamud.Data.DataManager..ctor(Dalamud dalamud) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 61
 ---> (Inner Exception #1) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Lumina.Data.LuminaBinaryReader.ReadStructure[T]()
   at Lumina.Data.SqPackIndex.LoadIndex()
   at Lumina.Data.SqPackIndex..ctor(FileInfo indexFile, GameData gameData)
   at Lumina.Data.Repository.<>c__DisplayClass28_1.<SetupIndexes>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

2023-10-11 22:01:04.642 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0xMC0xMVQyMjowMTowNC42NDI0NzY4KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uTnVsbFJlZmVyZW5jZUV4Y2VwdGlvbjogT2JqZWN0IHJlZmVyZW5jZSBub3Qgc2V0IHRvIGFuIGluc3RhbmNlIG9mIGFuIG9iamVjdC5cclxuICAgYXQgRGFsYW11ZC5EYXRhLkRhdGFNYW5hZ2VyLkdldEZpbGVbVF0oU3RyaW5nIHBhdGgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXERhdGFcXERhdGFNYW5hZ2VyLmNzOmxpbmUgMTUxXHJcbiAgIGF0IERhbGFtdWQuRGF0YS5EYXRhTWFuYWdlci5HZXRGaWxlKFN0cmluZyBwYXRoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxEYXRhXFxEYXRhTWFuYWdlci5jczpsaW5lIDE0M1xyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5HYW1lRm9udHMuR2FtZUZvbnRNYW5hZ2VyLjw+Y19fRGlzcGxheUNsYXNzOF8wLjwuY3Rvcj5iX18wKFN0cmluZyBmb250TmFtZSkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxHYW1lRm9udHNcXEdhbWVGb250TWFuYWdlci5jczpsaW5lIDU1XHJcbiAgIGF0IFN5c3RlbS5MaW5xLkVudW1lcmFibGUuU2VsZWN0QXJyYXlJdGVyYXRvcmAyLlRvQXJyYXkoKVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5HYW1lRm9udHMuR2FtZUZvbnRNYW5hZ2VyLi5jdG9yKERhdGFNYW5hZ2VyIGRhdGFNYW5hZ2VyKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEdhbWVGb250c1xcR2FtZUZvbnRNYW5hZ2VyLmNzOmxpbmUgNTVcclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIFZvaWQqKiBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gaXNDb25zdHJ1Y3RvcilcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uQ29uc3RydWN0b3JJbnZva2VyLkludm9rZShPYmplY3Qgb2JqLCBJbnRQdHIqIGFyZ3MsIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uQ29uc3RydWN0b3JJbnZva2VyLkludm9rZShPYmplY3Qgb2JqLCBJbnRQdHIqIGFyZ3MsIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5SdW50aW1lQ29uc3RydWN0b3JJbmZvLkludm9rZShCaW5kaW5nRmxhZ3MgaW52b2tlQXR0ciwgQmluZGVyIGJpbmRlciwgT2JqZWN0W10gcGFyYW1ldGVycywgQ3VsdHVyZUluZm8gY3VsdHVyZSlcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uQ29uc3RydWN0b3JJbmZvLkludm9rZShPYmplY3RbXSBwYXJhbWV0ZXJzKVxyXG4gICBhdCBEYWxhbXVkLlNlcnZpY2VgMS5Db25zdHJ1Y3RPYmplY3QoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxTZXJ2aWNle1R9LmNzOmxpbmUgMzA2XHJcbiAgIGF0IERhbGFtdWQuU2VydmljZWAxLjw+Yy48PFN0YXJ0TG9hZGVyPmJfXzlfMD5kLk1vdmVOZXh0KCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcU2VydmljZXtUfS5jczpsaW5lIDIxMiIsIkNvbnRleHQiOiJbU1ZDXSBTZXJ2aWNlPFwiR2FtZUZvbnRNYW5hZ2VyXCI+OiBDb25zdHJ1Y3Rpb24gZmFpbHVyZSJ9
2023-10-11 22:01:04.642 +01:00 [ERR] [SVC] Service<GameFontManager>: Construction failure
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Dalamud.Data.DataManager.GetFile[T](String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 151
   at Dalamud.Data.DataManager.GetFile(String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 143
   at Dalamud.Interface.GameFonts.GameFontManager.<>c__DisplayClass8_0.<.ctor>b__0(String fontName) in C:\goatsoft\companysecrets\dalamud\Interface\GameFonts\GameFontManager.cs:line 55
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Dalamud.Interface.GameFonts.GameFontManager..ctor(DataManager dataManager) in C:\goatsoft\companysecrets\dalamud\Interface\GameFonts\GameFontManager.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Dalamud.Service`1.ConstructObject() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 306
   at Dalamud.Service`1.<>c.<<StartLoader>b__9_0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 212
2023-10-11 22:01:04.642 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0xMC0xMVQyMjowMTowNC42NDI3MjY4KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IE9uZSBvciBtb3JlIGVycm9ycyBvY2N1cnJlZC4gKE9uZSBvciBtb3JlIGVycm9ycyBvY2N1cnJlZC4gKEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLikpXHJcbiAtLS0+IFN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IE9uZSBvciBtb3JlIGVycm9ycyBvY2N1cnJlZC4gKEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLilcclxuIC0tLT4gU3lzdGVtLlJlZmxlY3Rpb24uVGFyZ2V0SW52b2NhdGlvbkV4Y2VwdGlvbjogRXhjZXB0aW9uIGhhcyBiZWVuIHRocm93biBieSB0aGUgdGFyZ2V0IG9mIGFuIGludm9jYXRpb24uXHJcbiAtLS0+IFN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBEYWxhbXVkLkRhdGEuRGF0YU1hbmFnZXIuR2V0RmlsZVtUXShTdHJpbmcgcGF0aCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcRGF0YVxcRGF0YU1hbmFnZXIuY3M6bGluZSAxNTFcclxuICAgYXQgRGFsYW11ZC5EYXRhLkRhdGFNYW5hZ2VyLkdldEZpbGUoU3RyaW5nIHBhdGgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXERhdGFcXERhdGFNYW5hZ2VyLmNzOmxpbmUgMTQzXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLkdhbWVGb250cy5HYW1lRm9udE1hbmFnZXIuPD5jX19EaXNwbGF5Q2xhc3M4XzAuPC5jdG9yPmJfXzAoU3RyaW5nIGZvbnROYW1lKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEdhbWVGb250c1xcR2FtZUZvbnRNYW5hZ2VyLmNzOmxpbmUgNTVcclxuICAgYXQgU3lzdGVtLkxpbnEuRW51bWVyYWJsZS5TZWxlY3RBcnJheUl0ZXJhdG9yYDIuVG9BcnJheSgpXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLkdhbWVGb250cy5HYW1lRm9udE1hbmFnZXIuLmN0b3IoRGF0YU1hbmFnZXIgZGF0YU1hbmFnZXIpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcR2FtZUZvbnRzXFxHYW1lRm9udE1hbmFnZXIuY3M6bGluZSA1NVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgVm9pZCoqIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBpc0NvbnN0cnVjdG9yKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Db25zdHJ1Y3Rvckludm9rZXIuSW52b2tlKE9iamVjdCBvYmosIEludFB0ciogYXJncywgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Db25zdHJ1Y3Rvckludm9rZXIuSW52b2tlKE9iamVjdCBvYmosIEludFB0ciogYXJncywgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5Db25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuU2VydmljZWAxLkNvbnN0cnVjdE9iamVjdCgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFNlcnZpY2V7VH0uY3M6bGluZSAzMDZcclxuICAgYXQgRGFsYW11ZC5TZXJ2aWNlYDEuPD5jLjw8U3RhcnRMb2FkZXI+Yl9fOV8wPmQuTW92ZU5leHQoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxTZXJ2aWNle1R9LmNzOmxpbmUgMjEyXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgRGFsYW11ZC5TZXJ2aWNlTWFuYWdlci5Jbml0aWFsaXplRWFybHlMb2FkYWJsZVNlcnZpY2VzKCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcU2VydmljZU1hbmFnZXIuY3M6bGluZSAyNDQiLCJDb250ZXh0IjoiW1NWQ10gRmFpbGVkIHJlc29sdmluZyBzZXJ2aWNlcyJ9
2023-10-11 22:01:04.642 +01:00 [ERR] [SVC] Failed resolving services
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Exception has been thrown by the target of an invocation.))
 ---> System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Dalamud.Data.DataManager.GetFile[T](String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 151
   at Dalamud.Data.DataManager.GetFile(String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 143
   at Dalamud.Interface.GameFonts.GameFontManager.<>c__DisplayClass8_0.<.ctor>b__0(String fontName) in C:\goatsoft\companysecrets\dalamud\Interface\GameFonts\GameFontManager.cs:line 55
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Dalamud.Interface.GameFonts.GameFontManager..ctor(DataManager dataManager) in C:\goatsoft\companysecrets\dalamud\Interface\GameFonts\GameFontManager.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Dalamud.Service`1.ConstructObject() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 306
   at Dalamud.Service`1.<>c.<<StartLoader>b__9_0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 212
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Dalamud.ServiceManager.InitializeEarlyLoadableServices() in C:\goatsoft\companysecrets\dalamud\ServiceManager.cs:line 244

   ```

</details>

**Comment by Soreepeong** [comment]
Try repairing the game from XL, and apply font mods again after that. Last patch probably have had to touch the container file that font mod touches

**Comment by Daedren** [comment]
Repairing the game fixed it. Thanks.
