### ISSUE TITLE
[.net8] SignatureHelper can not initialize unmanaged function pointers

### ISSUE THREAD

**Issue by Ottermandias** [goatcorp/Dalamud#1539]
It seems like the SignatureHelper / GameInteropProvider is unable to infer the usage type of signatures provided for unmanaged delegates, for example in QoLBar, the initialization step at https://github.com/UnknownX7/QoLBar/blob/09a16b04420b9c7b110bea23edbd24d5b7535ad0/Game.cs#L130C31-L130C31
fails for this unmanaged function
https://github.com/UnknownX7/QoLBar/blob/09a16b04420b9c7b110bea23edbd24d5b7535ad0/Game.cs#L61

with
```
10:41:43.075 ERR | [QoLBar] Failed loading QoLBar!
10:41:43.075 ERR | Dalamud.Utility.Signatures.SignatureException: Invalid Signature attribute for QoLBar.Game.getHUDLayout: could not detect desired signature use, set SignatureUseFlags manually
10:41:43.075 ERR |    at Dalamud.Utility.Signatures.SignatureHelper.<>c__DisplayClass1_0.<Initialize>g__Invalid|4(String message, Boolean prepend, <>c__DisplayClass1_1&, <>c__DisplayClass1_2&) in C:\goatsoft\companysecrets\dalamud\Utility\Signatures\SignatureHelper.cs:line 73
10:41:43.075 ERR |    at Dalamud.Utility.Signatures.SignatureHelper.Initialize(Object self, Boolean log) in C:\goatsoft\companysecrets\dalamud\Utility\Signatures\SignatureHelper.cs:line 184
10:41:43.075 ERR |    at Dalamud.Hooking.Internal.GameInteropProviderPluginScoped.InitializeFromAttributes(Object self) in C:\goatsoft\companysecrets\dalamud\Hooking\Internal\GameInteropProviderPluginScoped.cs:line 45
10:41:43.075 ERR |    at QoLBar.Game.Initialize() in /work/repo/Game.cs:line 130
10:41:43.075 ERR |    at QoLBar.QoLBar.ReadyPlugin() in /work/repo/QoLBar.cs:line 72
```

**Comment by aers** [comment]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/reflection/8.0/function-pointer-reflection

**Comment by Ottermandias** [comment]
Yeah, I quickly tested it before PR'ing and it loads QoLBar again no issue - I don't know if it might cause any other issues with misidentification, but I wouldn't think so.

**Comment by KazWolfe** [comment]
Closing as merged.
