### ISSUE TITLE
"Can't set language" error prevents saving settings

### ISSUE THREAD

**Issue by monsterfurby** [goatcorp/Dalamud#1562]
I am currently encountering an issue where clicking "Save and Close" in the Settings menu will only cause the settings window to flicker (i.e. the window to re-render) but not save the settings. Any changes are not applied. Looking at the logs, this seems to be caused by the following issue.

I am using the current version on Windows 10.

```
LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0xMi0wNlQxMjozODoxNi45NTQzODg5KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5FeGNlcHRpb246IENhbid0IHNldCBjdXJyZW50IGxhbmd1YWdlIHRvIEVuZ2xpc2gsIHNpbmNlIGl0J3Mgbm90IGxvYWRlZC5cclxuICAgYXQgRGFsYW11ZC5Mb2MuTG9jYWxpemF0aW9uLnNldF9DdXJyZW50TGFuZ3VhZ2UoTGFuZ3VhZ2UgdmFsdWUpXHJcbiAgIGF0IERhbGFtdWQuTG9jLkxvY2FsaXphdGlvbi5MYW5ndWFnZUNoYW5nZWQoU3RyaW5nIGxhbmdDb2RlKVxyXG4gICBhdCBEYWxhbXVkLkxvY2FsaXphdGlvbi5TZXR1cFdpdGhMYW5nQ29kZShTdHJpbmcgbGFuZ0NvZGUpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXExvY2FsaXphdGlvbi5jczpsaW5lIDEzOFxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlNldHRpbmdzLldpZGdldHMuTGFuZ3VhZ2VDaG9vc2VyU2V0dGluZ3NFbnRyeS5TYXZlKCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxJbnRlcm5hbFxcV2luZG93c1xcU2V0dGluZ3NcXFdpZGdldHNcXExhbmd1YWdlQ2hvb3NlclNldHRpbmdzRW50cnkuY3M6bGluZSA2NVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlNldHRpbmdzLlNldHRpbmdzVGFiLlNhdmUoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEludGVybmFsXFxXaW5kb3dzXFxTZXR0aW5nc1xcU2V0dGluZ3NUYWIuY3M6bGluZSA1OVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlNldHRpbmdzLlNldHRpbmdzV2luZG93LlNhdmUoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEludGVybmFsXFxXaW5kb3dzXFxTZXR0aW5nc1xcU2V0dGluZ3NXaW5kb3cuY3M6bGluZSAyMDBcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuSW50ZXJuYWwuV2luZG93cy5TZXR0aW5ncy5TZXR0aW5nc1dpbmRvdy5EcmF3KCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxJbnRlcm5hbFxcV2luZG93c1xcU2V0dGluZ3NcXFNldHRpbmdzV2luZG93LmNzOmxpbmUgMTkxXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcV2luZG93aW5nXFxXaW5kb3cuY3M6bGluZSA0NzkiLCJDb250ZXh0IjoiW1dpbmRvd1N5c3RlbV0gRXJyb3IgZHVyaW5nIERyYXcoKTogRGFsYW11ZCBTZXR0aW5ncyMjI1hsU2V0dGluZ3MyIn0=
2023-12-06 12:38:16.954 +01:00 [ERR] [WindowSystem] Error during Draw(): Dalamud Settings###XlSettings2
System.Exception: Can't set current language to English, since it's not loaded.
   at Dalamud.Loc.Localization.set_CurrentLanguage(Language value)
   at Dalamud.Loc.Localization.LanguageChanged(String langCode)
   at Dalamud.Localization.SetupWithLangCode(String langCode) in C:\goatsoft\companysecrets\dalamud\Localization.cs:line 138
   at Dalamud.Interface.Internal.Windows.Settings.Widgets.LanguageChooserSettingsEntry.Save() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\Settings\Widgets\LanguageChooserSettingsEntry.cs:line 65
   at Dalamud.Interface.Internal.Windows.Settings.SettingsTab.Save() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\Settings\SettingsTab.cs:line 59
   at Dalamud.Interface.Internal.Windows.Settings.SettingsWindow.Save() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\Settings\SettingsWindow.cs:line 200
   at Dalamud.Interface.Internal.Windows.Settings.SettingsWindow.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\Settings\SettingsWindow.cs:line 191
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 479

```

**Comment by phytopius** [comment]
I am ancountering the same issue right now

`2024-08-24 13:56:11.924 +02:00 [ERR] [WindowSystem] Error during Draw(): Dalamud Settings###XlSettings2
System.Exception: Can't set current language to German, since it's not loaded.
   at Dalamud.Loc.Localization.set_CurrentLanguage(Language value)
   at Dalamud.Loc.Localization.LanguageChanged(String langCode)
   at Dalamud.Localization.SetupWithLangCode(String langCode) in C:\goatsoft\companysecrets\dalamud\\Localization.cs:line 137
   at Dalamud.Interface.Internal.Windows.Settings.Widgets.LanguageChooserSettingsEntry.Save() in C:\goatsoft\companysecrets\dalamud\\Interface\Internal\Windows\Settings\Widgets\LanguageChooserSettingsEntry.cs:line 67
   at Dalamud.Interface.Internal.Windows.Settings.SettingsTab.Save() in C:\goatsoft\companysecrets\dalamud\\Interface\Internal\Windows\Settings\SettingsTab.cs:line 59
   at Dalamud.Interface.Internal.Windows.Settings.SettingsWindow.Save() in C:\goatsoft\companysecrets\dalamud\\Interface\Internal\Windows\Settings\SettingsWindow.cs:line 254
   at Dalamud.Interface.Internal.Windows.Settings.SettingsWindow.Draw() in C:\goatsoft\companysecrets\dalamud\\Interface\Internal\Windows\Settings\SettingsWindow.cs:line 227
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
`
