### ISSUE TITLE
Issues with new font atlas code

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#1613]
@Soreepeong Some issues we've found after merging the new font atlas code:

Some plugins(like "Market board" from the official repo) will reliably fail to build a font atlas.
```
2024-01-18 15:16:04.860 -05:00 [ERR] [FontAtlasFactory] [Market board:RebuildFontsPrivateReal] 0x2628377463504: Failed (at 11ms)
System.InvalidOperationException: ImFontAtlas.Build failed
   at Dalamud.Interface.ManagedFontAtlas.Internals.FontAtlasFactory.BuildToolkit.DoBuild() in C:\goatsoft\companysecrets\dalamud\Interface\ManagedFontAtlas\Internals\FontAtlasFactory.BuildToolkit.cs:line 452
   at Dalamud.Interface.ManagedFontAtlas.Internals.FontAtlasFactory.DalamudFontAtlas.RebuildFontsPrivateReal(Boolean isAsync, Single scale) in C:\goatsoft\companysecrets\dalamud\Interface\ManagedFontAtlas\Internals\FontAtlasFactory.Implementation.cs:line 639
```

---

Some users noted a difference in the font after the merge, noting that it looks more pixelated. Is that related to gamma changes?
https://slow.pics/c/qkRVFevY

**Comment by goaaats** [comment]
Weird behavior with docking(default font at the top, alpha)
https://discord.com/channels/581875019861328007/1084906665343729725/1198018361280430252

**Comment by goaaats** [comment]
Not using the same gamma was a conscious choice as far as I'm aware, since the way it used to be was too strong. You can put it back that way using the font picker we just merged though.

**Comment by NotNite** [comment]
I can't attach a screenshot because privacy, but Chat 2 is now transparent when docked with other plugin windows.
