### ISSUE TITLE
Plugin Installer Failure When Installing Plugin.

### ISSUE THREAD

**Issue by Sebane1** [goatcorp/Dalamud#1825]
I'm forwarding this log from a user who was attempting to install Artemis Roleplaying Kit.
They reported that when they click install, the installer would just not attempt to install the plugin, 
Have not been able to reproduce this on my end when using the plugin installer.

Error of note appears to be the following at line 346 of PluginInstallerWindow.cs:
```
[ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.<>c__DisplayClass72_0.<StartInstall>b__1(Task`1 task) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 346
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
```

Full Log:
[dalamud (18).log](https://github.com/user-attachments/files/15650400/dalamud.18.log)

**Comment by goaaats** [comment]
Looks like that installation timed out, your plugin might be too large. We don't handle that well yet. I fixed this specific bug, there should at least be a proper error message now.
