### ISSUE TITLE
Universalis uploader barfed a 404 error

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#188]
```
2020-10-18 13:46:57.069 -04:00 [VRB] {"worldID":53,"itemID":2572,"listings":[{"listingID":0,"hq":false,"pricePerUnit":34,"quantity":1,"retainerName":"Ali-cat","retainerID":33777097239414576,"creatorName":"","onMannequin":false,"sellerID":18014498560383263,"creatorID":0,"stainID":0,"retainerCity":3,"lastReviewTime":1603011234,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":35,"quantity":1,"retainerName":"Tinkerbella","retainerID":33777097239986154,"creatorName":"","onMannequin":false,"sellerID":18014498562856438,"creatorID":0,"stainID":0,"retainerCity":2,"lastReviewTime":1602993559,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":50,"quantity":1,"retainerName":"Kaze-kun","retainerID":33777097239845097,"creatorName":"","onMannequin":false,"sellerID":18014498561840779,"creatorID":18014498561840779,"stainID":0,"retainerCity":1,"lastReviewTime":1603002345,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":90,"quantity":1,"retainerName":"Mystrali","retainerID":33777097239331958,"creatorName":"","onMannequin":false,"sellerID":18014498560114396,"creatorID":18014498560114396,"stainID":0,"retainerCity":1,"lastReviewTime":1603044624,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":100,"quantity":1,"retainerName":"Bojan","retainerID":33777097239960091,"creatorName":"","onMannequin":false,"sellerID":18014498561798095,"creatorID":18014498561798095,"stainID":0,"retainerCity":2,"lastReviewTime":1603019085,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":650,"quantity":1,"retainerName":"Luuz","retainerID":33777097239934058,"creatorName":"","onMannequin":false,"sellerID":18014498562719482,"creatorID":0,"stainID":0,"retainerCity":3,"lastReviewTime":1603042793,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":700,"quantity":1,"retainerName":"Anastera","retainerID":33777097239937404,"creatorName":"","onMannequin":false,"sellerID":18014498562687245,"creatorID":18014498562687245,"stainID":0,"retainerCity":3,"lastReviewTime":1602999685,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":999,"quantity":1,"retainerName":"A'lan-mandragoran","retainerID":33777097238443949,"creatorName":"","onMannequin":false,"sellerID":18014498550080801,"creatorID":0,"stainID":0,"retainerCity":10,"lastReviewTime":1603031315,"materia":[]},{"listingID":0,"hq":true,"pricePerUnit":1000,"quantity":1,"retainerName":"Theycallmebigdaddy","retainerID":33777097239972816,"creatorName":"","onMannequin":false,"sellerID":18014498562865971,"creatorID":18014498562865971,"stainID":0,"retainerCity":2,"lastReviewTime":1603026519,"materia":[]},{"listingID":0,"hq":true,"pricePerUnit":1000,"quantity":1,"retainerName":"Theycallmebigdaddy","retainerID":33777097239972816,"creatorName":"","onMannequin":false,"sellerID":18014498562865971,"creatorID":18014498562865971,"stainID":0,"retainerCity":2,"lastReviewTime":1603026519,"materia":[]},{"listingID":0,"hq":true,"pricePerUnit":1000,"quantity":1,"retainerName":"Theycallmebigdaddy","retainerID":33777097239972816,"creatorName":"","onMannequin":false,"sellerID":18014498562865971,"creatorID":18014498562865971,"stainID":0,"retainerCity":2,"lastReviewTime":1603026519,"materia":[]},{"listingID":0,"hq":true,"pricePerUnit":1000,"quantity":1,"retainerName":"Theycallmebigdaddy","retainerID":33777097239972816,"creatorName":"","onMannequin":false,"sellerID":18014498562865971,"creatorID":18014498562865971,"stainID":0,"retainerCity":2,"lastReviewTime":1603026519,"materia":[]},{"listingID":0,"hq":false,"pricePerUnit":2000,"quantity":1,"retainerName":"Damon-salvator","retainerID":33777097239916988,"creatorName":"","onMannequin":false,"sellerID":18014498562615461,"creatorID":18014498562615461,"stainID":0,"retainerCity":3,"lastReviewTime":1603034526,"materia":[]}],"uploaderID":18014498561155350}

2020-10-18 13:46:57.191 -04:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Dalamud.Game.Network.Universalis.MarketBoardUploaders.UniversalisMarketBoardUploader.Upload(MarketBoardItemRequest request)
   at Dalamud.Game.Network.NetworkHandlers.<>c__DisplayClass9_1.<OnNetworkMessage>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Dalamud.Game.Network.Universalis.MarketBoardUploaders.UniversalisMarketBoardUploader.Upload(MarketBoardItemRequest request)
   at Dalamud.Game.Network.NetworkHandlers.<>c__DisplayClass9_1.<OnNetworkMessage>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by daemitus** [comment]
```
2020-10-21 08:55:30.052 -04:00 [VRB] MarketTaxRates: limsa#22 grid#0 uldah#0 ish#2 kugane#0 cr#0
2020-10-21 08:56:00.866 -04:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.
...
   at Dalamud.Game.Network.Universalis.MarketBoardUploaders.UniversalisMarketBoardUploader.UploadTax(MarketTaxRates taxRates)
...
```
