### ISSUE TITLE
XIVAPI Looking up characters

### ISSUE THREAD

**Issue by Zyian** [goatcorp/Dalamud#24]
Experienced by `Jazzy#9999` on Discord.

> Have Discord bot setup

Dalamud output:
```
2019-12-31 16:33:06.058 -06:00 [ERR] Could not get XIVAPI character search result.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Dalamud.XivApi.<Get>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dalamud.XivApi.<GetCharacterSearch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dalamud.DiscordBot.DiscordBotManager.<GetCharacterInfo>d__19.MoveNext()
```

**Comment by Zyian** [comment]
I was able to reproduce a scenario to crash the game when setting up the discord bot. Having it configured with the token, I loaded into the game on one character, received the same error as above (`dalamud.txt`) then logged out and logged into a second character. At this point we receive the DirectX error which crashes the game

**Comment by goaaats** [comment]
This shouldn't apply anymore since we rewrote the whole code handling this a few months back - I don't think it's a problem with the new codebase, will keep an eye out
