### ISSUE TITLE
Dalamud windows sometimes not working

### ISSUE THREAD

**Issue by Aireil** [goatcorp/Dalamud#325]
The error in logs:
```
[ERR] Error while dispatching command /xlplugins (Argument: )
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dalamud.DalamudCommands.OnOpenInstallerCommand(String command, String arguments) in C:\goatsoft\companysecrets\dalamud\DalamudCommands.cs:line 270
   at Dalamud.Game.Command.CommandManager.DispatchCommand(String command, String argument, CommandInfo info) in C:\goatsoft\companysecrets\dalamud\Game\Command\CommandManager.cs:line 124
```

**Comment by goaaats** [comment]
We didn't run into this at all as of late, so I assume it's fixed in net5.
