### ISSUE TITLE
PartyFinderGui failed to dispose

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#510]
```
System.BadImageFormatException: Invalid access to memory location. (0x800703E6)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
   at Dalamud.Game.Gui.PartyFinder.PartyFinderGui.Dispose() in C:\Users\Raymond\code\Dalamud\Dalamud\Game\Gui\PartyFinder\PartyFinderGui.cs:line 69
```

**Comment by daemitus** [comment]
#514
