### ISSUE TITLE
Native/Mixed plugins fail to load

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#515]
We probably need a new manifest entry, or a try again in the plugin loader that sets this kind of plugin as not-unloadable/reloadable. 

```
14:10:17.712 | ERR [LOCALPLUGIN] Not a plugin: F:\ffxiv\NativeHousemate\x64\Debug\NativeHousemate.dll
System.BadImageFormatException: Cannot load a mixed assembly into a collectible AssemblyLoadContext.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path)
   at Dalamud.Plugin.Internal.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 66
```

**Comment by SheepGoMeh** [comment]
The repo for NativeHousemate is available [here](https://github.com/SheepGoMeh/NativeHousemate)

**Comment by goaaats** [comment]
I think it's better that we don't support this for now to save on complexity in the already complex plugin system. If theres a real need, we can always come back to it.
