### ISSUE TITLE
PluginManager not ready at OnLogin welcome message. LOL

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#517]
```
System.InvalidOperationException: Dalamud.Plugin.Internal.PluginManager has not been registered in the service locator!
   at Dalamud.Service`1.Get() in C:\Users\Raymond\code\Dalamud\Dalamud\Service{T}.cs:line 82
   at Dalamud.Game.ChatHandlers.PrintWelcomeMessage() in C:\Users\Raymond\code\Dalamud\Dalamud\Game\ChatHandlers.cs:line 254
   at Dalamud.Game.ChatHandlers.OnChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled) in C:\Users\Raymond\code\Dalamud\Dalamud\Game\ChatHandlers.cs:line 182
   at Dalamud.Game.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter) in C:\Users\Raymond\code\Dalamud\Dalamud\Game\Gui\ChatGui.cs:line 375
2021-08-29 08:20:01.643 -04:00 [VRB] [CHATGUI][][Tori Freya gains the effect of î‚»îœInner Quiet.]
2021-08-29 08:20:01.643 -04:00 [ERR] Exception on OnChatMessage hook.
```

**Comment by goaaats** [comment]
How did this happen? Must be a race condition, did you inject while being logged in in a busy area?

**Comment by daemitus** [comment]
late manual injection while logging into limsa

**Comment by daemitus** [comment]
only happens with manual injection (probably), wontfix.
