### ISSUE TITLE
Plugin Installer causes stuttering when icons/images are loaded

### ISSUE THREAD

**Issue by reiichi001** [goatcorp/Dalamud#634]
Basically the title. Users with a poor connection to GitHub / GCP are seeing the game stutter when they open the plugin installer. While this isn't generally an issue, some users are experiencing issues that continue through their session and it results in stuttering and FPS drops even after the plugin installer window has been closed.

Sample error:
```
2021-10-08 13:24:24.337 -07:00 [ERR] [PLUGINM] Error during install (update)
System.Net.Http.HttpRequestException: No such host is known. (us-central1-xl-functions.cloudfunctions.net:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken
```

**Comment by daemitus** [comment]
Each plugin's images are offloaded into a different task, so it may be
slamming them with concurrent connections to github. This isnt an issue
with the image download blocking.

Maybe we need a no-image option to just disable the downloads these people?

**Comment by Maxunit** [comment]
I notice the same every time I start the game fresh and open the Plugin Installer. It causes the game and my entire audio to stutter for a second or two while it loads the images. After that, it is fine (unless there are connection issues to Github)

**Comment by daemitus** [comment]
Mm .. maybe we're hitting a task limit and something important in framework
is being delayed
