### ISSUE TITLE
Tier 3 load is not being triggered

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#635]
Tier 3 load is never triggered. Present hook is probably not being called.

```021-10-10 14:56:11.051 +09:00 [INF] --------------------------------------------------------------------------------
2021-10-10 14:56:11.054 +09:00 [INF] Initializing a session..
2021-10-10 14:56:11.603 +09:00 [INF] [SVC] Registered Dalamud.Dalamud into service locator privately
2021-10-10 14:56:11.603 +09:00 [INF] [SVC] Registered Dalamud.DalamudStartInfo into service locator privately
2021-10-10 14:56:11.603 +09:00 [INF] [SVC] Registered Dalamud.Configuration.Internal.DalamudConfiguration into service locator privately
2021-10-10 14:56:11.603 +09:00 [INF] Starting a session..
2021-10-10 14:56:11.667 +09:00 [INF] [SVC] Registered Dalamud.IoC.Internal.ServiceContainer into service locator privately
2021-10-10 14:56:12.907 +09:00 [INF] [SVC] Registered Dalamud.Game.SigScanner into service locator and exposed to plugins
2021-10-10 14:56:12.908 +09:00 [INF] [SVC] Registered Dalamud.Hooking.Internal.HookManager into service locator privately
2021-10-10 14:56:14.081 +09:00 [INF] [T1] FFXIVClientStructs initialized!
2021-10-10 14:56:14.436 +09:00 [INF] [SVC] Registered Dalamud.Game.Framework into service locator and exposed to plugins
2021-10-10 14:56:14.437 +09:00 [INF] [T1] Framework OK!
2021-10-10 14:56:14.530 +09:00 [INF] [SVC] Registered Dalamud.Game.Network.GameNetwork into service locator and exposed to plugins
2021-10-10 14:56:14.640 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.ChatGui into service locator and exposed to plugins
2021-10-10 14:56:14.641 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.PartyFinder.PartyFinderGui into service locator and exposed to plugins
2021-10-10 14:56:14.706 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.Toast.ToastGui into service locator and exposed to plugins
2021-10-10 14:56:14.722 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.FlyText.FlyTextGui into service locator and exposed to plugins
2021-10-10 14:56:14.725 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.GameGui into service locator and exposed to plugins
2021-10-10 14:56:14.726 +09:00 [INF] [SVC] Registered Dalamud.Game.Libc.LibcFunction into service locator and exposed to plugins
2021-10-10 14:56:14.728 +09:00 [INF] [T1] Framework ENABLE!
2021-10-10 14:56:14.826 +09:00 [INF] [SVC] Registered Dalamud.Game.Internal.AntiDebug into service locator privately
2021-10-10 14:56:14.826 +09:00 [INF] [T2] AntiDebug OK!
2021-10-10 14:56:14.841 +09:00 [INF] [SVC] Registered Dalamud.Game.Network.Internal.WinSockHandlers into service locator privately
2021-10-10 14:56:14.841 +09:00 [INF] [T2] WinSock OK!
2021-10-10 14:56:14.841 +09:00 [INF] [SVC] Registered Dalamud.Game.Network.Internal.NetworkHandlers into service locator privately
2021-10-10 14:56:14.841 +09:00 [INF] [T2] NH OK!
2021-10-10 14:56:14.842 +09:00 [INF] [SVC] Registered Dalamud.Data.DataManager into service locator and exposed to plugins
2021-10-10 14:56:16.822 +09:00 [INF] Lumina is ready: Z:\Program\Game\FFXIV\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\sqpack
2021-10-10 14:56:16.822 +09:00 [INF] [T2] Data OK!
2021-10-10 14:56:17.005 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Objects.ObjectTable into service locator and exposed to plugins
2021-10-10 14:56:17.006 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Fates.FateTable into service locator and exposed to plugins
2021-10-10 14:56:17.006 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Party.PartyList into service locator and exposed to plugins
2021-10-10 14:56:17.006 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Buddy.BuddyList into service locator and exposed to plugins
2021-10-10 14:56:17.006 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.JobGauge.JobGauges into service locator and exposed to plugins
2021-10-10 14:56:17.006 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Keys.KeyState into service locator and exposed to plugins
2021-10-10 14:56:17.007 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.GamePad.GamepadState into service locator privately
2021-10-10 14:56:17.007 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Conditions.Condition into service locator and exposed to plugins
2021-10-10 14:56:17.007 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.Objects.TargetManager into service locator and exposed to plugins
2021-10-10 14:56:17.008 +09:00 [INF] [SVC] Registered Dalamud.Game.ClientState.ClientState into service locator and exposed to plugins
2021-10-10 14:56:17.008 +09:00 [INF] [T2] CS OK!
2021-10-10 14:56:17.008 +09:00 [INF] [SVC] Registered Dalamud.Localization into service locator privately
2021-10-10 14:56:17.008 +09:00 [INF] Trying to set up Loc for culture en
2021-10-10 14:56:17.010 +09:00 [INF] [T2] LOC OK!
2021-10-10 14:56:17.033 +09:00 [INF] [SVC] Registered Dalamud.Interface.Internal.Notifications.NotificationManager into service locator privately
2021-10-10 14:56:17.093 +09:00 [INF] ReShade DLL: Z:\Program\Game\FFXIV\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\d3d11.dll with DXGISwapChain::runtime_present at 7FFD8FF77FB0
2021-10-10 14:56:17.096 +09:00 [INF] [SVC] Registered Dalamud.Interface.Internal.InterfaceManager into service locator privately
2021-10-10 14:56:17.097 +09:00 [INF] [T2] IM OK!
2021-10-10 14:56:17.097 +09:00 [INF] [SVC] Registered Dalamud.Game.Gui.Internal.DalamudIME into service locator privately
2021-10-10 14:56:17.097 +09:00 [INF] [T2] IME OK!
2021-10-10 14:56:17.097 +09:00 [INF] [SVC] Registered Dalamud.Game.Text.SeStringHandling.SeStringManager into service locator and exposed to plugins
2021-10-10 14:56:17.097 +09:00 [INF] [T2] SeString OK!
2021-10-10 14:56:17.115 +09:00 [INF] [SVC] Registered Dalamud.Game.Command.CommandManager into service locator and exposed to plugins
2021-10-10 14:56:17.115 +09:00 [INF] [SVC] Registered Dalamud.Interface.Internal.DalamudCommands into service locator privately
2021-10-10 14:56:17.116 +09:00 [INF] [T2] CM OK!
2021-10-10 14:56:17.124 +09:00 [INF] [SVC] Registered Dalamud.Game.ChatHandlers into service locator and exposed to plugins
2021-10-10 14:56:17.124 +09:00 [INF] [T2] CH OK!
2021-10-10 14:56:17.124 +09:00 [INF] [T2] CS ENABLE!
2021-10-10 14:56:17.193 +09:00 [INF] [SVC] Registered Dalamud.Game.Internal.DalamudAtkTweaks into service locator privately
2021-10-10 14:57:31.766 +09:00 [ERR] Exception on OnChatMessage hook.
System.InvalidOperationException: Dalamud.Plugin.Internal.PluginManager has not been registered in the service locator!
   at Dalamud.Service`1.Get() in C:\goatsoft\companysecrets\dalamud\Service{T}.cs:line 82
   at Dalamud.Game.ChatHandlers.PrintWelcomeMessage() in C:\goatsoft\companysecrets\dalamud\Game\ChatHandlers.cs:line 238
   at Dalamud.Game.ChatHandlers.OnChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled) in C:\goatsoft\companysecrets\dalamud\Game\ChatHandlers.cs:line 183
   at Dalamud.Game.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter) in C:\goatsoft\companysecrets\dalamud\Game\Gui\ChatGui.cs:line 380```

**Comment by daemitus** [comment]
Any other details? I agree with the present hook, but as to why it didn't work, why knows.

**Comment by goaaats** [comment]
This happens on way outdated (Re|G)Shade installations that have the DXGI code, but don't use it. Probably to check for via file version.
What's the best way to solve this? Run a timer that checks if tier 3 has loaded 30 seconds after tier 2 did,

**Comment by daemitus** [comment]
we now have logging for this.
