### ISSUE TITLE
Catch this pluginManager error and handle appropriately

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#659]
```2021-10-26 15:12:24.403 +02:00 [ERR] Plugin load failed.
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'IconUrl', line 10, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dalamud.Plugin.Internal.PluginManager.LoadAllPlugins() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 227
   at Dalamud.Dalamud.LoadTier3() in C:\goatsoft\companysecrets\dalamud\Dalamud.cs:line 268```

**Comment by Aireil** [comment]
Pretty sure it is good now.
