### ISSUE TITLE
ObjectDisposedException when exiting game

### ISSUE THREAD

**Issue by ghost** [goatcorp/Dalamud#728]
```
[INF]TROUBLESHOOTING:eyJMb2FkZWRQbHVnaW5zIjpbXSwiRGFsYW11ZFZlcnNpb24iOiI2LjIuMC4xNiIsIkRhbGFtdWRHaXR 
IYXNoIjoiOWI4YzU0MSIsIkdhbWVWZXJzaW9uIjoiMjAyMS4xMi4yNC4wMDAwLjAwMDAiLCJMYW5ndWFnZSI6IkVuZ2xpc2giLCJEb0RhbGFtdWRUZXN0IjpmYWxzZSwiQmV0YUtleSI6bnVsbCwiRG9QbHVnaW5UZXN0IjpmYWxzZSwiSW50ZXJmYWNlTG9hZGVkIjp0cnVlLCJGb3JjZWRNaW5Ib29rIjpmYWxzZSwiVGhpcmRSZXBvIjpbXSwiSGFzVGhpcmRSZXBvIjp0cnVlfQ==
[FTL] Unhandled exception on AppDomain
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Dalamud.Interface.Internal.Windows.PluginImageCache.DownloadTask() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginImageCache.cs:line 180
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
Seems to be reproducible but doing so is fairly obscure. 
Open game to title screen, activate dev menu, open plugin installer then immediately exit the game.

**Comment by Aireil** [comment]
Pretty sure this no longer happens.
