### ISSUE TITLE
Installer dying on image cache issue

### ISSUE THREAD

**Issue by Aireil** [goatcorp/Dalamud#913]
I added a dev plugin, then the installer just died and took ImGui styling with it.
I'm on 6.4.0.31 (8d33252), this is spammed in the log, I don't really get what's that 192 line, even looking in the history:
```
[ERR] [Dalamud] Error during OnDraw
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Dalamud.Interface.Internal.Windows.PluginImageCache.TryGetIcon(LocalPlugin plugin, PluginManifest manifest, Boolean isThirdParty, TextureWrap& iconTexture) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginImageCache.cs:line 192
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.DrawPluginCollapsingHeader(String label, LocalPlugin plugin, PluginManifest manifest, Boolean isThirdParty, Boolean trouble, Boolean updateAvailable, Boolean isNew, Action drawContextMenuAction, Int32 index) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 1052
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.DrawInstalledPlugin(LocalPlugin plugin, Int32 index, Boolean showInstalled) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 1499
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.DrawInstalledPluginList() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 592
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.DrawPluginCategoryContent() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 723
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.DrawPluginCategories() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 655
   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 181
   at Dalamud.Interface.Windowing.Window.DrawInternal() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 195
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 117
   at Dalamud.Interface.Internal.DalamudInterface.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\DalamudInterface.cs:line 420
```

**Comment by Aireil** [comment]
OK it's because internal name is null in the manifest lol.
Idk if Dalamud should really expect that or care for it, shouldn't really happen.
